/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  frontEndSidebar: [
    'front-end/index',
    {
      type: 'category',
      label: 'Javascript',
      items: [
        {
          type: 'autogenerated',
          dirName: 'front-end/js',
        },
      ],
    },
    {
      type: 'category',
      label: 'Css',
      items: [
        {
          type: 'autogenerated',
          dirName: 'front-end/css',
        },
      ],
    },
    {
      type: 'category',
      label: 'React',
      items: [
        {
          type: 'autogenerated',
          dirName: 'front-end/react',
        },
      ],
    },
  ],
  utilsSiderBar: [
    'utils/index',
    {
      type: 'category',
      label: 'git',
      items: [
        {
          type: 'autogenerated',
          dirName: 'utils/git',
        },
      ],
    },
  ],
};
